#+TITLE: Notes_steve

Be boneheaded --

ignore everything but wood costs.

wood increases constantly

canopy closes, total amount of carbon gain is constant, amount per tree gained per time is constant. Biomass grows linearly after canopy closed.

Use old-fashioned PPA -- w/ water only model we have density independent death.

With tree model when we have DI death,



Maximize the Z* -- there is a maximum. LRS depends on growth rate of the tree. L is inversely related to growth rate is inversely related to H growth rate. think about the log ? divided by G to allometric power. sum of logs from strigul. If growth rate is inversely proportional to allocation to stem, then there exists a stem allocation high enough that you cant replace yourself even in full sun.


for shrubs -- tops curved a little bit. taller species closing off. Everybody crowds into remaining places ?

If canopy were closed whole time. suppose that after disturbance, canopy closes effectively instantaneously, and suppose that everybody who is in the understory dies. Amount of leaf area is constant. timescale for water, no water is short. If you have out vs. up -- total amount of transpiration stays constant?

Build a simulator -- productive enough that it closed the canopy quickly.

- expect shrubs to be -- if there were a period of oppenness after the burn. is it sensible for a plant to invest in stem early.

each year there is more total biomass -- 1 type, amount of time they have to grow shrinks. Given current size and number can solve what that time is. know the photosynthetic rate at. for particular plant size can compute growth rate. Growth as a function of size.

growth goes as 1 over size. ds/dt = s/(1+s) michaelis menten almost ds/dt = constant times s, then constant.

like light limited stem. when D gets big enough D/(1+D). when D is small, grows exponentially.

-- when first closes, Z* is zero. As soon as there is significant gap phase competition, LRS of an individual growing in full sun is huge. If it is that big, it wont bounce. Gap where it gets bouncy. Three kinds of mortality -- disturbance related deaths, density dependent deaths, density independent deaths,

-- how can it be that strategies you see out there. Predicts landscape patterns that are obvious.

* Nitrogen

- only think about N mineralization rate. They access N. Passively taking up N vs paying for N. Mychoriz have a game where it is adaptive to keep the price constant. Economic reason why mychorizzae. Keep a constant price. Economics of mychorizzae. Thesis could be --

* CO2
range of strategies that can coexist depends on wetness at start of rainstorm. On the one hand you are growing faster, but if its subsumed inside photosynthesis.
- one of the only models where you could look mechanistically at the impact of climate change -- wet places get wetter and

- saturation deficits increased by temperatures alone.
- CO2 fert increases. CO2 and temp effect decoupled.
- CO2 fert all else equal will end season earlier and make it drier for everything else.
- latest strategy species

* N
- microbes harvest certain amount of N through the year.
- N tax covers cost of N shortage.
- flow restriction on hose causes diameter to be large. SA to volume ratio on hose makes it poor soil water absorber. Cost of complexity -- causes symbionts.
- growth rates don't slow down.
- Implications -- if you are worried about productivity and whole ecosystem output. If youre


- other body of experimental work showing that Nitrogen does limit growth. Try a bunch of other models -- N is supplied by mycorrhizal.
  Britain group, general model. One that has the highest ratio of resource A to resource B. Competitive process produces an efficient market. Implications -- if we are right, all plants can get N


FIRE -
- IRA has funding for management.
