#+TITLE: Water competition in perennial plants
#+AUTHOR: Jacob Levine


* Growth rate

Consider a system of competing perennial plants in which rain arrives in a fixed amount, \(P\), at regular intervals of length, \(T\). We assume a separation of timescales such that plants accumulate carbon at a rate, \(\overline{C_1}\), defined as the average rate of carbon accumulation during the period in which species 1's stomates are open. During the period in which species 1's stomates are closed, it transpires at rate \(C_2\). Thus, an individual's total carbon accumulation over the inter-rain period is given by:

\begin{equation}
  C(t_1) = \left(\frac{t_1}{T}\right)\overline{C_1} - \left(\frac{T-t_1}{T}\right)C_2
\end{equation}

where \(t_1\) is the time at which species 1's stomates close completely. Next, we assume an age-structured population with density-independent mortality at rate \(\mu\) and power-law allometry such that the biomass of an individual in the \(j\)'th cohort is given by:

\begin{equation}
  B_{1,j} =  e^{-\mu j T} G(C(t_1))^B (j T)^B
\end{equation}

where cohorts are stratified by inter-rain interval, \(G()\) is a function which converts carbon accumulation to growth rate, and \(B\) is the allometric exponent for biomass.

The total biomass of species 1 is then given by:

\begin{equation}
B_{1} = \sum_{j=1}^{\infty} e^{-\mu j T} G(C(t_1))^B (j T)^B
\end{equation}

* Break-even time

Assuming that individuals reproduce once per interrain interval, at the end of the interval, the lifetime reproductive success of an individual is given by:

\begin{equation}
L_1 = F_1 G(C(t_1))^B T^B \sum_{j=1}^{\infty} e^{-\mu j T} j^B
\end{equation}

we now rewrite this equation as:

\begin{equation}
L_1^{1/B} = F_1^{1/B} G(C(t_1)) T \sum_{j=1}^{\infty} j e^{\frac{-\mu T}{B}j}
\end{equation}

and solving the infinite sum find

\begin{equation}
L_1^{1/B} = F_1^{1/B} G(C(t_1)) T  \frac{e^{\frac{-\mu T}{B}}}{\left(1 - e^{\frac{-\mu T}{B}} \right)^2}
\end{equation}

We now solve for \(t_i\) which gives lifetime reproductive success equal to one, we call this time \(t_i^*\), the break-even time. First we plug in an expression for \(G(C(t_1))\) and set \(L_1 = 1\):

\begin{equation}
1 = F_1^{1/B} \frac{\nu-1}{\nu \delta} \left[\left(\frac{t_1^*}{T}\right)\overline{C_1} - \left(\frac{T-t_1^*}{T} \right) C_2 \right] T  \frac{e^{\frac{-\mu T}{B}}}{\left(1 - e^{\frac{-\mu T}{B}} \right)^2}
\end{equation}

solving for \(t_1^*\) we find:

\begin{equation}
t_1^* = \frac{1}{\overline{C_1} + C_2} \left[ \frac{\nu \delta}{\nu - 1} \left(\frac{1}{F_1}\right)^{\frac{1}{B}} \frac{\left(1 - e^{\frac{-\mu T}{B}} \right)^2}{e^{\frac{-\mu T}{B}}}  + T C_2\right]
\end{equation}

* Equilibrium density and water dynamics

First for a single species

\begin{equation}
W_0 - W_1^* = N_1^* E t_1^* G(C(t_1^*))^{L} T^L  \left(\frac{e^{\frac{-\mu T}{B}}}{\left(1 - e^{\frac{-\mu T}{B}} \right)^2}\right)^L
\end{equation}

where \(W_0 = R\) if \(R < W_{max}\) and \(W_0 = W_{max}\) if \(R > W_{max}\) (\(W_{max}\) is the field capacity of the soil).

\begin{equation}
W_0 - W_1^* = N_1^* E t_1^* \left(\frac{1}{F_1}\right)^{\frac{B-1}{B}}
\end{equation}

\begin{equation}
 N_1^* = F_1^{\frac{B-1}{B}}\left(\frac{W_0 - W_1^*}{E t_1^*}\right)
\end{equation}

For Q species:

\begin{equation}
N_i^* = \frac{F_1^{\frac{B-1}{B}}}{E}\left[\frac{\Delta W_i^*}{\Delta t_i^*} - \frac{\Delta W_{i+1}^*}{\Delta t_{i+1}^*} \right]
\end{equation}

which implies that species \(i\) has a feasible equilibrium provided the following conditions are met:

\begin{equation*}
\(\frac{\Delta W_i^*}{\Delta t_i^*} > \frac{\Delta W_{i+1}^*}{\Delta t_{i+1}^*}\)
\begin{equation*}

\begin{equation*}
 t_i^* < T
\end{equation*}

and,

\begin{equation*}
W_i^* < W_0
\end{equation*}





** Water + Matteo's light

*** Cases:

1. Taller species are also less drought tolerant, strict hierarchy. Matches with empirical correlations in Liu et al 2019 Science Advances.
   - For 2 species, this is basically the same as Matteo's model, as for multiple water strategies to coexist they must result in identical average growth per interrain interval.
   - So far, assume that plant growth rates are constant in the period before canopy closes. Do this by assuming that total evapotranspiration is not high enough to cause least tolerant species to reach its shutoff until after the canopy closes. At this point, water drawdown in first period is constant because total leaf area = 1, growth of second species is dependent on earlier species but this doesnt matter because its leaf area is determined only by taller species growth rate, which is constant.
